### ISSUE TITLE
installation

### ISSUE THREAD

**Issue by metrue** [fatiherikli/klassify#1]
I installed everything per README and ran it, but met following issue, can you advise ?

```
Traceback (most recent call last):
  File "/USR/LOCAL/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 151, in _run_module_as_main
    mod_name, loader, code, fname = _get_module_details(mod_name)
  File "/USR/LOCAL/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 109, in _get_module_details
    return _get_module_details(pkg_main_name)
  File "/USR/LOCAL/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 101, in _get_module_details
    loader = get_loader(mod_name)
  File "/USR/LOCAL/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/pkgutil.py", line 464, in get_loader
    return find_loader(fullname)
  File "/USR/LOCAL/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/pkgutil.py", line 474, in find_loader
    for importer in iter_importers(fullname):
  File "/USR/LOCAL/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/pkgutil.py", line 430, in iter_importers
    __import__(pkg)
  File "/USR/LOCAL/lib/python2.7/site-packages/klassify/__init__.py", line 1, in <module>
    from klassify import *
  File "/USR/LOCAL/lib/python2.7/site-packages/klassify/klassify.py", line 9, in <module>
    from backend.handlers import (
  File "/USR/LOCAL/lib/python2.7/site-packages/klassify/backend/handlers.py", line 9, in <module>
    from .tokenizer import tokenize
  File "/USR/LOCAL/lib/python2.7/site-packages/klassify/backend/tokenizer.py", line 4, in <module>
    stop = stopwords.words('english')
  File "/USR/LOCAL/lib/python2.7/site-packages/nltk/corpus/util.py", line 99, in __getattr__
    self.__load()
  File "/USR/LOCAL/lib/python2.7/site-packages/nltk/corpus/util.py", line 64, in __load
    except LookupError: raise e
LookupError:
**********************************************************************
  Resource u'corpora/stopwords' not found.  Please use the NLTK
  Downloader to obtain the resource:  >>> nltk.download()
  Searched in:
    - '/Users/ming/nltk_data'
    - '/usr/share/nltk_data'
    - '/usr/local/share/nltk_data'
    - '/usr/lib/nltk_data'
    - '/usr/local/lib/nltk_data'
**********************************************************************

```

**Comment by Salakar** [comment]
@metrue you can solve this by running:

`python -c 'import nltk; nltk.download("stopwords")'`

**Comment by metrue** [comment]
@Salakar  thank you for your quick response.

I am not python guy, but I think it does not handle the dependencies well here. 
I have no idea how should I take care everything like afterward. 

```
➜  klassify git:(master) ✗ python -m klassify
/USR/LOCAL/opt/python/bin/python2.7: No module named http.client; 'klassify' is a package and cannot be directly executed
➜  klassify git:(master) ✗ python --version
Python 2.7.10

```

**Comment by Salakar** [comment]
Neither am I hah, the above worked for me though, on OSX. 

I installed via `pip`, then ran the stop words installer, after that it works here.

Not sure what the other issue is about to be honest. I tried hah :star:

**Comment by fatiherikli** [comment]
While in the development directory, you can directly run the klassify instead of module loading method.

This would help to you:

```
python klassify/klassify.py
```

**Comment by LuRsT** [comment]
A bit offtopic to this issue but, one thing that I'd add to the installation instructions @fatiherikli would be to make sure/install redis, even thought its in the description that it uses redis, it could be more explicit for people that simply jump to the installation instructions :smiley:

**Comment by metrue** [comment]
@fatiherikli 

I did install klassify via pip

<code> pip install klassify <code>

but  

<code> python -m klassify </code> 

met error as above.

@LuRsT 

thanks for you information, someone come up with a detail instruction would be great, maybe it's pointless for someone, but useful for some kind of people like me.

**Comment by LuRsT** [comment]
I'll send a PR about redis installation :+1:

**Comment by davidterranova** [comment]
Same error while installing the following way:
```sh
# OS X 10.11.3
brew install python redis
pip install klassify
python -m klassify

/usr/local/opt/python/bin/python2.7: No module named http.client; 'klassify' is a package and cannot be directly executed
```

**Comment by LuRsT** [comment]
What is the output from your pip install klassify? You probably need a `sudo pip install`, or create a virtualenv like this:

    # You may need to install virtual-env-wrapper, maybe brew install virtualenv-wrapper?
    mkvirtualenv klassify
    pip install klassify
    python -m klassify

**Comment by fatiherikli** [comment]
Can you try `python -m klassify.__main__` @LuRsT

**Comment by davidterranova** [comment]
Here is the output with your command line :
`/usr/local/opt/python/bin/python2.7: No module named http.client`
@fatiherikli

**Comment by fatiherikli** [comment]
This is really interesting. Probably this is an environment problem because We hadn't used any module that named `http`

**Comment by LuRsT** [comment]
@fatiherikli That command doesn't work on my environment (which is correctly configured).

@davidterranova I meant the output from the pip command, can you execute it again?

**Comment by fatiherikli** [comment]
Did you activate your virtual environment? @davidterranova

**Comment by davidterranova** [comment]
I successfully installed `virtualenv` with `pip`
However `mkvirtualenv` is unknown.

Here is the pip output:
```
pip install klassify
Requirement already satisfied (use --upgrade to upgrade): klassify in /usr/local/lib/python2.7/site-packages
Requirement already satisfied (use --upgrade to upgrade): nltk==3.1 in /usr/local/lib/python2.7/site-packages (from klassify)
Requirement already satisfied (use --upgrade to upgrade): tornado==4.3 in /usr/local/lib/python2.7/site-packages (from klassify)
Requirement already satisfied (use --upgrade to upgrade): tornado-redis==2.4.18 in /usr/local/lib/python2.7/site-packages (from klassify)
Requirement already satisfied (use --upgrade to upgrade): certifi in /usr/local/lib/python2.7/site-packages (from tornado==4.3->klassify)
Requirement already satisfied (use --upgrade to upgrade): backports-abc>=0.4 in /usr/local/lib/python2.7/site-packages (from tornado==4.3->klassify)
Requirement already satisfied (use --upgrade to upgrade): backports.ssl-match-hostname in /usr/local/lib/python2.7/site-packages (from tornado==4.3->klassify)
Requirement already satisfied (use --upgrade to upgrade): singledispatch in /usr/local/lib/python2.7/site-packages (from tornado==4.3->klassify)
Requirement already satisfied (use --upgrade to upgrade): six in /usr/local/lib/python2.7/site-packages (from singledispatch->tornado==4.3->classify)
```

**Comment by fatiherikli** [comment]
To clarify: This is my personal computer (OSX) and I'm running this command.

```
sudo pip install klassify
python -m klassify
```

I did not get any error and It worked fine. 

So you don't need a virtual environment.

**Comment by davidterranova** [comment]
Same here @fatiherikli

**Comment by LuRsT** [comment]
@davidterranova that pip output looks completely fine to me, you should definitely be able to do

    python -m klassify

or

    cd /usr/local/lib/python2.7/dist-packages
    python -m klassify

**Comment by davidterranova** [comment]
@LuRsT From the directory `/usr/local/lib/python2.7/site-packages` cause `dost-packages` does not exists

```
Traceback (most recent call last):
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 151, in _run_module_as_main
    mod_name, loader, code, fname = _get_module_details(mod_name)
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 109, in _get_module_details
    return _get_module_details(pkg_main_name)
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 101, in _get_module_details
    loader = get_loader(mod_name)
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/pkgutil.py", line 464, in get_loader
    return find_loader(fullname)
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/pkgutil.py", line 474, in find_loader
    for importer in iter_importers(fullname):
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/pkgutil.py", line 430, in iter_importers
    __import__(pkg)
  File "klassify/__init__.py", line 1, in <module>
    from klassify import *
  File "klassify/klassify.py", line 9, in <module>
    from backend.handlers import (
  File "klassify/backend/handlers.py", line 9, in <module>
    from .tokenizer import tokenize
  File "klassify/backend/tokenizer.py", line 4, in <module>
    stop = stopwords.words('english')
  File "nltk/corpus/util.py", line 99, in __getattr__
    self.__load()
  File "nltk/corpus/util.py", line 64, in __load
    except LookupError: raise e
LookupError:
**********************************************************************
  Resource u'corpora/stopwords' not found.  Please use the NLTK
  Downloader to obtain the resource:  >>> nltk.download()
  Searched in:
    - '/Users/davidterranova/nltk_data'
    - '/usr/share/nltk_data'
    - '/usr/local/share/nltk_data'
    - '/usr/lib/nltk_data'
    - '/usr/local/lib/nltk_data'
**********************************************************************
```

**Comment by LuRsT** [comment]
@davidterranova In that case, try running:

    python -c 'import nltk; nltk.download("stopwords")'

**Comment by davidterranova** [comment]
@LuRsT Working ! Thanks!

**Comment by fatiherikli** [comment]
All the pull requests about this issue have been merged. So I'm closing this issue now. 

Thanks everyone!
