### ISSUE TITLE
Gives error when try to train or classify

### ISSUE THREAD

**Issue by enod** [fatiherikli/klassify#5]
Result of the log: 

[E 160314 15:18:17 web:1524] Uncaught exception POST /train (127.0.0.1)
    HTTPServerRequest(protocol='http', host='127.0.0.1:8888', method='POST', uri='/train', version='HTTP/1.1', remote_ip='127.0.0.1', headers={'Accept': '*/*', 'Host': '127.0.0.1:8888', 'Accept-Language': 'en-US,en;q=0.8,mn;q=0.6,zh-TW;q=0.4,zh;q=0.2', 'Content-Length': '370', 'Referer': 'http://localhost:8888/', 'Origin': 'http://localhost:8888', 'Accept-Encoding': 'gzip, deflate', 'Content-Type': 'text/plain;charset=UTF-8', 'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.87 Safari/537.36', 'Connection': 'keep-alive'})
    Traceback (most recent call last):
      File "/Users/bal/.pyenv/versions/venv-3/lib/python3.5/site-packages/tornado/web.py", line 1445, in _execute
        result = yield result
      File "/Users/bal/.pyenv/versions/venv-3/lib/python3.5/site-packages/tornado/gen.py", line 1008, in run
        value = future.result()
      File "/Users/bal/.pyenv/versions/venv-3/lib/python3.5/site-packages/tornado/concurrent.py", line 232, in result
        raise_exc_info(self._exc_info)
      File "<string>", line 3, in raise_exc_info
      File "/Users/bal/.pyenv/versions/venv-3/lib/python3.5/site-packages/tornado/gen.py", line 282, in wrapper
        yielded = next(result)
      File "/Users/bal/Development/klassify/klassify/backend/handlers.py", line 58, in post
        text, label = self.get_json('text', 'label')
      File "/Users/bal/Development/klassify/klassify/backend/handlers.py", line 22, in get_json
        data = json.loads(self.request.body)
      File "/Users/bal/.pyenv/versions/3.5.1/lib/python3.5/json/__init__.py", line 312, in loads
        s.__class__.__name__))
    TypeError: the JSON object must be str, not 'bytes'
[E 160314 15:18:17 web:1946] 500 POST /train (127.0.0.1) 1.13ms

**Comment by enod** [comment]
Tried on python 2.7.10 which gives -  UnicodeEncodeError: 'ascii' codec can't encode characters in position 6-10: ordinal not in range(128)

**Comment by enod** [comment]
It started working after I FLUSHALL redis database.
