### ISSUE TITLE
can not runn

### ISSUE THREAD

**Issue by wongchsh** [fatiherikli/klassify#9]
after i install the klassify.  I got an error as follow:
C:\Users\ibm>python -m klassify
Traceback (most recent call last):
  File "C:\Python\Python35\lib\runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Python\Python35\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Python\Python35\lib\site-packages\klassify\__main__.py", line 1, in <module>
    from klassify import main
ImportError: cannot import name 'main'

**Comment by hongjiw** [comment]
I have the same problem

**Comment by hongjiw** [comment]
It works when I rollback to python 2.7.
